app = "anniexboda-5ncltw"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "performance"  # لازم performance عشان يقبل 16 كور
  cpus = 16                 # 16 Cores
  memory_mb = 92160         # 90 GB RAM (90 * 1024)
